# Generated by Django 5.0 on 2024-08-01 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_mpesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesa',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.order'),
            preserve_default=False,
        ),
    ]
