# Generated by Django 5.0 on 2024-08-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_mpesa_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesa',
            name='checkout_request_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mpesa',
            name='merchant_request_id',
            field=models.CharField(max_length=100),
        ),
    ]
