# Generated by Django 5.0 on 2024-08-02 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_mpesa_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_postal_code',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_city',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_country',
        ),
    ]
